                                                                                                                                                                                                                                                               
Delivered-To: recipient@emailaddress.com
Received: by 172.0.0.1 with SMTP id l12abc1234567xyz;
        Sat, 7 Feb 2015 20:43:09 -0800 (PST)
X-Received: by 172.0.0.2 with SMTP id 123456789abcdefg;
        Sat, 07 Feb 2015 20:43:08 -0800 (PST)
Return-Path: <sender@emailaddress.com>
Received: from my.mail.host (my.mail.host. [172.0.0.3])
        by another.mail.host with ESMTPS id qwerty456789
        for <recipient@emailaddress.com>
        (version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Sat, 07 Feb 2015 20:43:07 -0800 (PST)
Received: by my.mail.host (Postfix, from userid 1000)
	id 456fgh789; Sat,  7 Feb 2015 23:53:49 -0500 (EST)
Date: Sat, 07 Feb 2015 23:53:49 -0500
To: recipient@emailaddress.com
Subject: This is cool.
User-Agent: Heirloom mailx 12.5 6/20/10
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
Message-Id: <789456123hjkyuinm@my.mail.host>
From: sender@emailaddress.com (Sender Name)

Thanks!
